// Production Bun server for StudyBub.
// Starts the TanStack Start server built with the Bun Nitro preset.
// Run with: bun run server.ts

// The built server handler is produced by `vinxi build` with preset: "bun".
// It lives under the output directory (often .output/server/index.mjs).
// This thin wrapper resolves and starts it.

// The built server module does not exist until after `bun run build`.
// @ts-expect-error - module is generated by the build step.
const serverEntry = await import(".output/server/index.mjs");

// The default export of the built server is a fetch-compatible handler.
// Bun.serve accepts a fetch handler directly.
const handler = serverEntry.default ?? serverEntry.fetch;

if (typeof handler !== "function") {
  console.error(
    "Server handler not found. Run `bun run build` first to build the production server.",
  );
  process.exit(1);
}

const port = Number(process.env.PORT) || 3000;

Bun.serve({
  port,
  fetch: handler,
});

console.log(`StudyBub server running on http://localhost:${port}`);
