/**
 * Production Bun server for StudyBub.
 *
 * Starts the TanStack Start server built with the Nitro Bun preset.
 * The built server module auto-starts - we only need to import it.
 * Run with: bun run start  (or bun run scripts/server.ts)
 *
 * @author John Grimes
 */

// The built server module lives under .output/server/index.mjs.
// The path is relative to this file's location (scripts/).
// Nitro auto-starts its own server, so we just need to import it.
// @ts-expect-error - module is generated by the build step, no types.
await import("../.output/server/index.mjs");

console.log("StudyBub server started (Nitro auto-managed).");
